version: '3.5'
services:

  postgres-service:
    container_name: postgres-service
    image: postgres:11
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: password
      POSTGRES_DB: orders

  zookeeper:
    container_name: zookeeper
    image: zookeeper:3.4.12
    ports:
      - "2181:2181"
    environment:
      zk_id: "1"

  kafka-broker:
    container_name: kafka
    image: wurstmeister/kafka:2.11-2.0.1
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_CREATE_TOPICS: orders
      KAFKA_BROKER_ID: 1
