spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/orders
    username: appuser
    password: password
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect.